"""Синхронизация ядра alla в Qwen Code скилл ``alla-launch``.

Скилл живёт в проекте автотестов и не может зависеть от установленного
пакета ``alla``. Поэтому чистые модули ядра (TestOps-клиент, триаж,
извлечение логов, кластеризация, сборка промптов) копируются в
``qwen-skill/alla-launch/scripts/alla_core/`` без изменений логики:
переписываются только import-строки ``alla.`` → ``alla_core.``.

``alla_core/config.py`` — рукописный shim (не копия ``alla/config.py``),
генератор его не трогает, но проверяет, что вендоренный код обращается
только к полям ``Settings``, которые в shim есть.

Использование::

    python tools/sync_qwen_skill.py          # перегенерировать alla_core
    python tools/sync_qwen_skill.py --check  # проверить отсутствие дрейфа
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_ROOT = REPO_ROOT / "src" / "alla"
CORE_ROOT = REPO_ROOT / "qwen-skill" / "alla-launch" / "scripts" / "alla_core"

PACKAGE = "alla_core"
SHIM_MODULES = {"config"}

MANIFEST: tuple[str, ...] = (
    "exceptions.py",
    "clients/auth.py",
    "clients/base.py",
    "clients/testops_client.py",
    "knowledge/feedback_models.py",
    "knowledge/feedback_signature.py",
    "knowledge/models.py",
    "models/clustering.py",
    "models/common.py",
    "models/llm.py",
    "models/testops.py",
    "services/attachment_handlers.py",
    "services/clustering_service.py",
    "services/log_extraction_service.py",
    "services/prompt_builder_service.py",
    "services/triage_service.py",
    "utils/log_utils.py",
    "utils/step_paths.py",
    "utils/text_normalization.py",
)

_IMPORT_RE = re.compile(r"^(\s*)(from|import)(\s+)alla(?=[.\s])", re.MULTILINE)
_HEADER = "# GENERATED by tools/sync_qwen_skill.py from src/alla/{path} — do not edit.\n"
_PACKAGE_HEADER = "# GENERATED by tools/sync_qwen_skill.py — do not edit.\n"


class SyncError(Exception):
    """Вендоринг невозможен: манифест или shim не покрывают зависимости."""


def _module_name(rel_path: str) -> str:
    return rel_path.removesuffix(".py").replace("/", ".")


def _alla_imports(tree: ast.AST) -> list[str]:
    """Вернуть все импортируемые модули пакета alla (включая вложенные импорты)."""
    modules: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
            names = [node.module]
        elif isinstance(node, ast.Import):
            names = [alias.name for alias in node.names]
        else:
            continue
        modules.extend(
            name for name in names if name == "alla" or name.startswith("alla.")
        )
    return modules


def _settings_attributes(tree: ast.AST) -> set[str]:
    """Собрать обращения вида ``settings.<attr>``."""
    return {
        node.attr
        for node in ast.walk(tree)
        if isinstance(node, ast.Attribute)
        and isinstance(node.value, ast.Name)
        and node.value.id == "settings"
    }


def shim_fields() -> set[str]:
    """Поля ``Settings`` из рукописного shim ``alla_core/config.py``."""
    tree = ast.parse((CORE_ROOT / "config.py").read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == "Settings":
            return {
                item.target.id
                for item in node.body
                if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name)
            }
    raise SyncError("В alla_core/config.py не найден класс Settings")


def render_module(rel_path: str, source: str) -> str:
    """Переписать import-строки и добавить заголовок GENERATED."""
    tree = ast.parse(source)
    expected = len(_alla_imports(tree))
    rewritten, replaced = _IMPORT_RE.subn(rf"\1\2\3{PACKAGE}", source)
    if replaced != expected:
        raise SyncError(
            f"{rel_path}: найдено {expected} импортов alla, "
            f"переписано {replaced} — проверьте формат import-строк"
        )
    return _HEADER.format(path=rel_path) + rewritten


def generate() -> dict[Path, str]:
    """Сгенерировать содержимое alla_core: {путь относительно CORE_ROOT: текст}."""
    known_modules = {_module_name(path) for path in MANIFEST} | SHIM_MODULES
    fields = shim_fields()
    files: dict[Path, str] = {Path("__init__.py"): _PACKAGE_HEADER}
    problems: list[str] = []

    for rel_path in MANIFEST:
        source = (SRC_ROOT / rel_path).read_text(encoding="utf-8")
        tree = ast.parse(source)
        for module in _alla_imports(tree):
            local = module.removeprefix("alla").removeprefix(".")
            if local not in known_modules:
                problems.append(f"{rel_path}: импорт {module} не входит в MANIFEST")
        missing = _settings_attributes(tree) - fields
        if missing:
            problems.append(
                f"{rel_path}: settings.{', settings.'.join(sorted(missing))} "
                "нет в shim alla_core/config.py"
            )
        files[Path(rel_path)] = render_module(rel_path, source)
        for parent in Path(rel_path).parents:
            if parent != Path("."):
                files.setdefault(parent / "__init__.py", _PACKAGE_HEADER)

    if problems:
        raise SyncError("\n".join(problems))
    return files


def _existing_generated() -> set[Path]:
    return {
        path.relative_to(CORE_ROOT)
        for path in CORE_ROOT.rglob("*.py")
        if "__pycache__" not in path.parts
        and path.relative_to(CORE_ROOT).with_suffix("").as_posix() not in SHIM_MODULES
    }


def check() -> list[str]:
    """Вернуть список расхождений между src/alla и alla_core (пусто — дрейфа нет)."""
    expected = generate()
    issues: list[str] = []
    for rel, text in sorted(expected.items()):
        target = CORE_ROOT / rel
        if not target.exists():
            issues.append(f"отсутствует {rel}")
        elif target.read_text(encoding="utf-8") != text:
            issues.append(f"устарел {rel}")
    for rel in sorted(_existing_generated() - set(expected)):
        issues.append(f"лишний {rel}")
    return issues


def write() -> int:
    """Перезаписать alla_core и удалить устаревшие сгенерированные файлы."""
    expected = generate()
    for rel in _existing_generated() - set(expected):
        (CORE_ROOT / rel).unlink()
    for rel, text in expected.items():
        target = CORE_ROOT / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
    return len(expected)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="только проверить дрейф")
    args = parser.parse_args(argv)
    try:
        if args.check:
            issues = check()
            if issues:
                print("alla_core расходится с src/alla:", file=sys.stderr)
                for issue in issues:
                    print(f"  - {issue}", file=sys.stderr)
                print("Запустите: python tools/sync_qwen_skill.py", file=sys.stderr)
                return 1
            print("alla_core синхронизирован с src/alla")
            return 0
        count = write()
    except SyncError as exc:
        print(f"Ошибка синхронизации:\n{exc}", file=sys.stderr)
        return 2
    print(f"alla_core обновлён: {count} файлов")
    return 0


if __name__ == "__main__":
    sys.exit(main())
